### PR TITLE
CLOUD-3142 - move CD / EAP base configuration modules to a more structured format

### PR DESCRIPTION
**Pull request by luck3y**
https://issues.jboss.org/browse/CLOUD-3142
Signed-off-by: Ken Wills <kwills@redhat.com>

### CODE REVIEW

**Comment by luck3y** [comment]
@bstansberry This is an early version of this change, and it needs a bit more testing. Basically the idea is we want to make module management a bit easier for variations of the base configurations. EAP 7.2 on JDK 11 has some base configuration changes, so rather than creating a top level module, we'd create jboss-openshift/config/eap/7.2.0-JDK11 as a module, (for example) and maintain the configurations there.

This provides legacy support for the previous config modules, but marks them as deprecated, we could perhaps drop them around CD17 time, or perhaps further out.

**Comment by luck3y** [comment]
cc: @jmesnil - Jeff some of your CD16 stuff got moved into this new structure, and since that is all new, I didn't leave the top level module, as there was nothing to keep compatible with just yet.

**Comment by bstansberry** [comment]
@luck3y the 14 module can be dropped now.  We need a module for the current live image and the current in dev image.

**Comment by luck3y** [comment]
Ok, good idea, I was being cautious.

**Comment by luck3y** [comment]
actually i may move these under the jboss/ subdirectory, now that I'm thinking about it more.

**Comment by luck3y** [comment]
Moved to namespace jboss/container/config to match more closely what we already have, and still be generic.

**Comment by bstansberry** [comment]
Before we do this kind of thing I think we should get the necessary maintenance branches established.

**Comment by bstansberry** [comment]
@luck3y Please remove the 'hold' label when this is ready for review.

**Comment by luck3y** [comment]
Closing this for now, will revisit.

**Pull request closed without merging**
