### PR TITLE
CLOUD-3509 correct misspelling / typo of keystore

### PR DESCRIPTION
**Pull request by luck3y**
https://issues.redhat.com/browse/CLOUD-3509
Signed-off-by: Ken Wills <kwills@redhat.com>

### CODE REVIEW

**Comment by yersan** [comment]
@luck3y , sorry, I forgot about reviewing this PR and now it got stale. Maybe you could force it again so I can give a look?

**Comment by luck3y** [comment]
Note these GHA actions failures don't happen locally, I'll update when I've located the issue (probably a shell difference in ubuntu vs Fedora / RHEL or something.)

**Comment by luck3y** [comment]
@yersan This has been updated, can you have a look? Not sure why this got lost in the mist!

**Review by yersan — APPROVED** [review]

**Comment by TomasHofman** [comment]
@yersan @luck3y I cherry-picked this commit to 7.3.x branch, can you also review and merge that?

I don't know how to run test, `./run-all-tests.sh` doesn't do anything, but the cherry-pick was smooth :).

**Pull request merged**
