### PR TITLE
[CLOUD-3606] - Legacy EAP 7.3 standalone configuration for OpenShift

### PR DESCRIPTION
**Pull request by luck3y**
https://issues.redhat.com/browse/CLOUD-3606
Signed-off-by: Ken Wills <kwills@redhat.com>

### CODE REVIEW

**Comment by luck3y** [comment]
@jmesnil FYI this only exists on the 7.3.x-legacy branch, and is for layered product use only, we don't have any other uses.

**Comment by spolti** [comment]
@luck3y just built and tested an image here, everything goes well.

**Comment by spolti** [comment]
@luck3y @jmesnil any updates?

**Comment by spolti** [comment]
Hi @jmesnil do you have nay updates on this?

**Pull request merged**
