### PR TITLE
CLOUD-3022 Drop use_ip_addrs="true" workaround

### PR DESCRIPTION
**Pull request by rhusar**
Jira
https://issues.jboss.org/browse/CLOUD-3022

### CODE REVIEW

**Comment by rhusar** [comment]
Needs to be retested.

**Comment by luck3y** [comment]
We do seem to get similar behaviour with things not using this though, for example: https://issues.jboss.org/browse/CLOUD-2996?focusedCommentId=13663672&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-13663672

But we can certainly take it out and see what happens.

**Comment by bstansberry** [comment]
I don't have the details in front of me anymore but when experimenting last night using dns.DNS_PING but with this turned off I saw errors that reminded me of what I recall as being the reason we added this in the first place.

I'll try again later and if I see the problem I'll post the details.

**Comment by rhusar** [comment]
@bstansberry I assume it would be remind of [this](https://issues.jboss.org/browse/JBEAP-14477?focusedCommentId=13550657&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13550657). The assumption here is that this was caused by the encryption issue(s) that were already addressed. Needs more testing.

**Comment by luck3y** [comment]
FWIW: I've tested dns.DNS_PING and openshit.DNS_PING (patched locally version) and I didn't see the connection refused spam.

**Comment by bstansberry** [comment]
@rhusar Yes, I believe it was the " WARN [org.jgroups.protocols.TCP] (TQ-Bundler-7,ee,eap-app-1-hm47k) JGRP000032: eap-app-1-hm47k: no physical address" message from your link.  I'm  confident it mentioned TQ-Bundler, and pretty confident is said something about a physical or logical address, as that's what made me think it might be related to turning off use_ip_addrs.

In any case, I've done lots of experimentation this afternoon and haven't seen this again. And I can't say for sure what happened yesterday; there's some chance it was with openshift.DNS_PING (although I thik not.)  Anyway, I'm fine with this change if it produces better results in QE tests.  I can't see any sign in my personal testing that it makes things worse.

**Comment by luck3y** [comment]
Was included in https://github.com/jboss-container-images/jboss-eap-modules/pull/40. Thanks Rado!

**Pull request closed without merging**
