### PR TITLE
[CLOUD-3213] - [7.2.x-openjdk11] Update bats tests to run with new CI

### PR DESCRIPTION
**Pull request by luck3y**
https://issues.jboss.org/browse/CLOUD-3213
Upstream PR: https://github.com/jboss-container-images/jboss-eap-modules/pull/67
Signed  off by: Ken WIlls <kwills@redhat.com>

### CODE REVIEW

**Comment by luck3y** [comment]
@bstansberry The 7.2.x and 7.2.x-openjdk issues are all fine to go as part of CP, see: https://issues.jboss.org/browse/CLOUD-3219 and https://issues.jboss.org/browse/CLOUD-3215 for the lists of issues approved for both.

**Comment by bstansberry** [comment]
@luck3y I'd approve this but CI says the test is failing.

**Comment by luck3y** [comment]
@bstansberry Hmm, I'd thought these were all failing for the same reason (something in CI), thx for noticing, will take a look shortly...

**Comment by luck3y** [comment]
This also requires: https://github.com/jboss-container-images/jboss-eap-modules/pull/102 to fix issues around xmllint.

**Pull request merged**
