### PR TITLE
CLOUD-3198 Datasource generation should escape ampersand

### PR DESCRIPTION
**Pull request by slaskawi**
https://issues.jboss.org/browse/CLOUD-3198

This Pull Request fixes the ampersand in URL parsing problem. the problem might be reproduced by using `DB_URL=jdbc:postgresql://172.17.0.2:5432/rhsso&ssl=true`. Without this Pull Request, the connection url would be trimmed to `jdbc:postgresql://172.17.0.2:5432/rhsso` (without `&ssl=true`). 

Dear EAP Team - I'm not sure where would you like to test this feature out. Perhaps it would be best if you could add one commit on top of mine, and implement proper test (in any place you'd like it to be).

@iankko @luck3y  Please take a look at this PR once you have a chance.

### CODE REVIEW

**Comment by luck3y** [comment]
@slaskawi LGTM thanks!

**Comment by ricardozanini** [comment]
@luck3y we might need to add semicolon to the escape list as well. Look: https://github.com/jboss-container-images/jboss-kie-modules/pull/245

**Comment by luck3y** [comment]
@slaskawi WDYT about @ricardozanini's comment? Is there an issue with ;? I suppose you can have a ; in a URL.

**Comment by slaskawi** [comment]
@luck3y @ricardozanini I'm definitely for including the `;` fix into this Pull Request. However, I'd like to leave this one to you @luck3y as I'm not sure how would you like to implement that.

Obviously, the easiest way is to cherry-pick the changes proposed by @ricardozanini. You can also write something similar to what I did. Here's an example:

```
local url="${14//&/\\&}"
url="${url//;/\\;}"
```

**Comment by slaskawi** [comment]
@luck3y @ricardozanini Implemented.

**Comment by luck3y** [comment]
@slaskawi Thanks a lot Sebastian!

**Comment by luck3y** [comment]
Note: I'll open a seperate Jira to add tests for this.

**Pull request merged**
