### PR TITLE
[CLOUD-2784] - provide expressions to enable undertow and activemq statistics

### PR DESCRIPTION
**Pull request by luck3y**
https://issues.jboss.org/browse/CLOUD-2784
Signed-off-by: Ken Wills <kwills@redhat.com>

### CODE REVIEW

**Comment by luck3y** [comment]
Pushed to fix test.

**Comment by bstansberry** [comment]
This is missing the transactions and datasource stuff from https://github.com/wildfly/wildfly/pull/11916/files

**Comment by luck3y** [comment]
This should be g2g for master. The changes are cherry-pickable back for EAP 7.2 with the exception of the datasource one

**Comment by luck3y** [comment]
@bstansberry I've added CD14/15 and 7.1 to this change as well. I'll leave them as seperate commits so I can cherry-pick into the 72 branch.

**Pull request merged**
