### PR TITLE
[JBEAP-18124] fixing transaction_isolation setting for non-xa datasou…

### PR DESCRIPTION
**Pull request by istudens**
…rces

https://issues.redhat.com/browse/JBEAP-18124

### CODE REVIEW

**Comment by istudens** [comment]
@luck3y Could you review this please? I am going to port it back to other branches once it is reviewed. Thanks.

**Comment by luck3y** [comment]
@istudens LGTM, thanks!

**Comment by luck3y** [comment]
@istudens At a minimum you'll need a matching PR for this against the 7.2.x-openjdk11 and 7.3.x-legacy branches too. Does the same issue exist in master?

**Comment by istudens** [comment]
PRs for 7.2.x-openjdk11 and 7.3.x-legacy branches filed. I am not sure about master. I am not even able to run tests there.

**Pull request merged**
