### PR TITLE
[CLOUD-3206] Add default hostname ports to SSO client configuration

### PR DESCRIPTION
**Pull request by ricardozanini**
See:
https://issues.jboss.org/browse/CLOUD-3206
https://issues.jboss.org/browse/RHPAM-1336

Signed-off-by: Ricardo Zanini <zanini@redhat.com>

### CODE REVIEW

**Comment by luck3y** [comment]
@ricardozanini This is fine to go into master, but it  might be a bit too enhancementy to get into stable. Is this something you absolutely need in 7.2.x-* as well?

**Comment by ricardozanini** [comment]
@luck3y this is part of RHPAM-1336 that is schedule for 7.4.0, which is using the 7.2.x branch. But if you think that might require more tests (and I agree with you), I can talk to my team to push it to 7.4.1, so we would have more time to test.

**Comment by luck3y** [comment]
@ricardozanini It would be nice to have more tests yes, but also we need to cut off whats going in ASAP so we can merge to the stable branches on Monday, and if we keep putting stuff in that going to be more difficult.

**Comment by ricardozanini** [comment]
@luck3y this will be pushed to the next version. Don't bother merging this to a stable branch, but we should need this on the next cut.

**Comment by luck3y** [comment]
@ricardozanini OK, sounds fine to me. Do you want to close this issue for now?

**Comment by ricardozanini** [comment]
@luck3y yeah, we can definitely close this issue and merge this PR targeting the next stable version :)

**Comment by ricardozanini** [comment]
@luck3y I'll rebase this one, can you consider merging it?

**Comment by luck3y** [comment]
@ricardozanini Yeah, I'll merge it, but we're frozen for CD17 atm, i'll do it right after i put in the final tag.

**Comment by ricardozanini** [comment]
@luck3y thanks! just rebased the branch

**Comment by ricardozanini** [comment]
Hi @luck3y! Do you have an estimate of when we could have this one merged? Sorry to be a pain, but I'm moving to another project and I'm afraid I won't have the time to backtrack this issue once I got another responsibilities there :(

**Comment by luck3y** [comment]
@ricardozanini Thanks for the reminder, this can go in now.

**Pull request merged**
