### PR TITLE
[CLOUD-3470] Add behave tests for jpa-dist and ejb-dist-cache

### PR DESCRIPTION
**Pull request by yersan**
Add behave tests to verify jpa-dist and ejb-dist-cache Galleon layers

Jira issue: https://issues.redhat.com/browse/CLOUD-3470
Requires: https://github.com/jboss-container-images/jboss-eap-modules/pull/218

### CODE REVIEW

**Comment by yersan** [comment]
Hello @luck3y Only Bats tests are running on jboss-eap-modules, is that expected by you? I would rather expect to see here the behave tests as well, WDYT?

**Comment by luck3y** [comment]
> Hello @luck3y Only Bats tests are running on jboss-eap-modules, is that expected by you? I would rather expect to see here the behave tests as well, WDYT?

The challange is that this repo doesn't produce an image, and is shared. The projects consuming it though will run the behave tests on their images, but I think we're limited to using bats here (though I've been meaning to add ShellCheck as well.)

**Review by jfdenise — DISMISSED** [review]

**Comment by yersan** [comment]
Hello @luck3y , this is ready for merge.

**Comment by yersan** [comment]
Hello @luck3y, any chances to get this merged? It should be done before feature freeze, thanks!

**Review by luck3y — APPROVED** [review]

**Pull request merged**
