### PR TITLE
CLOUD-2331 EAP CD Image

### PR DESCRIPTION
**Pull request by luck3y**
These are the shared modules used by the EAP CD images. 

- the maven override is temporary until CLOUD-2365 is fixed.

### CODE REVIEW

**Comment by luck3y** [comment]
@bstansberry Review please :)

**Comment by rcernich** [comment]
I think all the maven stuff needs to remain in cct_module.  Most of that is shared by all the images.  We should be working to standardize on what is used by the openjdk image for the maven build/configuration, then have product specific extensions for copying things like data, configuration, etc.

**Comment by luck3y** [comment]
@rcernich Yep, agreed this is only until https://issues.jboss.org/browse/CLOUD-2365 is fixed which will hopefully be sometime tomorrow.

**Comment by luck3y** [comment]
I'm going to merge this for now so the openshift image build isn't broken, will remove the maven stuff shortly after cct_module fix goes into jboss-maven.

**Pull request merged**
