### PR TITLE
CLOUD-3179 - update CTF tests for CD16

### PR DESCRIPTION
**Pull request by luck3y**
https://issues.jboss.org/browse/CLOUD-3179
Signed-off-by: Ken Wills <kwills@redhat.com>

### CODE REVIEW

**Comment by bstansberry** [comment]
Seems ok, although I'm not sure why some of this isn't part of the other PRs.

**Comment by luck3y** [comment]
I can add this to the PR for creating the image, it was opened afterwards and I kept it under a different jira to track it. I think it could be useful to keep these seperate for when people have questions on what has to change in tests for a new image etc.

**Comment by luck3y** [comment]
FYI, this needs an update for the incorrect modules drop, will be updated in a sec

**Comment by luck3y** [comment]
Conflicts resolved, should be all set now.

**Pull request merged**
