### PR TITLE
[CLOUD-3287][CLOUD-3280] Add the CD 17 standalone-openshift.xml; configure the tm object store

### PR DESCRIPTION
**Pull request by bstansberry**
https://issues.jboss.org/browse/CLOUD-3287
https://issues.jboss.org/browse/CLOUD-3280

Signed-off-by: Brian Stansberry <brian.stansberry@redhat.com>

### CODE REVIEW

**Comment by luck3y** [comment]
@bstansberry FWIW, I made a new container for these so they wouldn't continuously enlarge the top level directory: https://github.com/jboss-container-images/jboss-eap-modules/tree/master/jboss-eap-config-openshift -- but if this doesn't work or you dislike it for some reason we should discuss.

**Comment by bstansberry** [comment]
Ok, will do.

**Comment by bstansberry** [comment]
@luck3y Done. I went with CD17.0 since you suggested it and it seems more precise.

**Comment by luck3y** [comment]
retest this please

**Pull request merged**
